server.port=8080


#spring.data.mongodb.uri=mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL}/techchallenge?retryWrites=true&w=majority&appName=Cluster0&ssl=true&tls=true
spring.data.mongodb.uri=mongodb+srv://danielaleixocorrea35_db_user:L0nXON3qf1VoGEvj@cluster0.yj9s4qv.mongodb.net/locadora?retryWrites=true&w=majority&appName=Cluster0&ssl=true&tls=true


#spring.jackson.default-property-inclusion=NON_NULL

api.mercadolivre.orders=https://api.mercadopago.com/instore/orders/qr/seller/collectors/1423020936/pos/DANICAIXA01/qrs
api.mercadolivr.token=TEST-7847449179180884-072110-5b05cf6195417ca341935a011741dbdb-1423020936
api.mercadolivre.payment=https://api.mercadolibre.com/merchant_orders

webhook.pipedream.net=
