server.port=8082

#spring.data.mongodb.uri=mongodb://root:example@localhost:27017/techchallenge
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=techchallenge
spring.data.mongodb.username=root
spring.data.mongodb.password=example



#spring.jackson.default-property-inclusion=NON_NULL

api.mercadolivre.orders=https://api.mercadopago.com/instore/orders/qr/seller/collectors/1423020936/pos/DANICAIXA01/qrs
api.mercadolivr.token=TEST-7847449179180884-072110-5b05cf6195417ca341935a011741dbdb-1423020936
api.mercadolivre.payment=https://api.mercadolibre.com/merchant_orders


webhook.pipedream.net=https://eogk4e0gy2wck7w.m.pipedream.net

logging.level.com.techchallenge.infrastructure.external.MercadoLivreOrders=DEBUG

